# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.addOne_arma <- function(x) {
    .Call(`_mlpack_Rpkg_addOne_arma`, x)
}

.addOne_rcpp <- function(x) {
    .Call(`_mlpack_Rpkg_addOne_rcpp`, x)
}

.knnDemo <- function(Reference, Query, k, verbose = FALSE) {
    .Call(`_mlpack_Rpkg_knnDemo`, Reference, Query, k, verbose)
}

